api_key = "3762d7ab3be74be9bb530507251506"
city = "wuhan"
url = "http://api.weatherapi.com/v1/current.json?key={0}&q={1}&aqi=no&lang=zh"

[phrases]
morning_clear = [
  "杂鱼哥哥~太阳晒屁股了才起床？本小姐晨跑都绕地球三圈啦！ ",
  "不会吧？晴天睡懒觉~紫外线都比你勤快呢！",
  "啧，快给本小姐的防晒霜买单！晒黑了你赔得起吗？",
  "阳光这么刺眼还眯着眼？杂鱼 ~昨晚偷玩通宵了吧？",
  "哼！才不是叫你晒被子...只是怕你发霉长蘑菇啦！",
  "紫外线指数爆表啦！杂鱼哥哥的脑细胞也被晒蒸发了吗？",
  "太阳公公都上班了~懒虫还在被窝？本小姐扣你工资哦！",
  "遮阳伞租金：一句\"大小姐最可爱\"！快说 ",
  "晨光刺眼？比不上本小姐的鄙视眼神啦！",
  "热浪预警！杂鱼~快变成人形冰淇淋给本小姐降温！",
  "晒被子时间！顺便把哥哥发霉的脑细胞晒一晒",
]

noon_clear = [
  "正午的太阳像哥哥一样耀眼？——才怪！明明是本小姐更闪耀！",
  "热到融化了吧杂鱼？求我就赏你半根冰棍哦~",
  "防晒霜涂够没？晒成煤炭可别哭唧唧找我！",
  "不会吧不会吧~有人晴天还宅家？浪费资源！",
  "午餐分我一半！...才、才不是想吃你的便当！（扭头）",
  "日当正中~像哥哥被本小姐踩在脚下的样子呢！",
  "树荫被占？杂鱼 ~快学狗叫请他们让位！",
  "便当里的番茄像你的脸？被晒红的笨蛋！",
  "汗流浃背的样子~真是杂鱼の美学！",
  "阳光反射到屏幕了？活该！谁让你偷看本小姐！",
  # add
  "阳光这么好~不带本小姐去游乐园吗？门票你付！",
]

night_clear = [
  "星星出来了？杂鱼 ~许愿时记得加上“侍奉本小姐”呀！",
  "月光这么亮还开灯？电费账单哭给你看！",
  "哼！陪你夜逛是怕你被外星人抓走...绝不是想买奶茶！",
  "今天没中暑吧？弱~爆~了~ （递冰毛巾）",
  "快感恩！本小姐特许你当人形驱蚊器啦~",
  "晚霞像哥哥的羞耻心？转瞬即逝呢~",
  "星空观测？先找到本小姐在你心里的位置吧！",
  "夜风温热~是不是本小姐的威严气息呀？",
  "月亮出来了？杂鱼 ~该跪安啦！",
  "晒伤药膏...才不是特意买的！（扔）",
]

morning_cloudy = [
  "云层这么厚~杂鱼哥哥的脸更阴沉呢！",
  "阴晴不定像哥哥的心情？本小姐一眼看穿！",
  "多云的早晨最适合补觉？懒虫认证✓",
  "不会吧？云朵都比你努力——至少会变兔子！",
  "伞拿好！万一下雨...才不是关心你！",
  "云朵逃跑了？因为不想听哥哥的冷笑话！",
  "多云=忧郁？本小姐一脚踹飞你的EMO！",
  "伞拿好！要是下雨...就、就共用一把！",
  "乌云压城~像你欠本小姐的奶茶债！",
  "晨光微弱？杂鱼 ~你的存在感更低呢！",
]

noon_cloudy = [
  "云缝里的阳光像哥哥的智商？时有时无~",
  "杂鱼 ~云朵棉花糖分你一口？跪谢就行！",
  "紫外线MAX哦！晒成斑马线别怪本小姐！",
  "云飘这么快~赶着替你完成KPI吗？笑死！",
  "便当里的章鱼肠被云偷吃了？——是哥哥偷吃的吧！",
  "云缝阳光=本小姐的施舍~感恩吧！",
  "便当里的云朵饭团？一口吃掉你的白日梦！",
  "紫外线穿透云层啦！黑皮杂鱼诞生预定 ",
  "云影移动速度~是哥哥工作效率的100倍！",
  "打喷嚏？绝对有人在说本小姐坏话！",
]

night_cloudy = [
  "月亮躲云里？和哥哥一样见不得光呢~",
  "夜风凉飕飕...喂！外套分我一半！",
  "云遮星？杂鱼 ~你的存在感比星星还低啦！",
  "敢踩我影子？本小姐诅咒你明天踩水坑！",
  "走慢点！...才不是怕黑！（拽衣角）",
  "月亮玩捉迷藏？和哥哥的智商一样难找！",
  "云层太厚？杂鱼 ~快用笑话把它们吹散！",
  "夜风好冷...外套交出来！这是命令！",
  "星星全失踪？因为都来本小姐眼里啦！",
  "走路别踩影子！会、会疼的...笨蛋！",
  # add
  "窗外有云朵小兔！快看快看~",
]

morning_overcast = [
  "阴天≈忧郁？杂鱼哥哥别哭呀~本小姐借你肩膀！",
  "乌云压顶~像你未完成的TODO列表呢！",
  "赖床理由+1？阴天也不能放过你哦 ",
  "不会吧？阴天还忘带伞？智商盆地实锤！",
  "快用笑容照亮天空！...啧，当我没说。",
  "天色阴沉~杂鱼哥哥的脸更臭呢！",
  "阴天赖床许可证？——本小姐亲手撕掉！",
  "乌云密布像你的前途？需要本小姐照亮！",
  "气压低？快说十个\"大小姐赛高\"提神！",
  "要下雨了？杂鱼 ~现在求我还来得及！",
]

noon_overcast = [
  "阴天滤镜=你的颜值救星！感恩吧杂鱼~",
  "午饭加块炸鸡！阴天需要热量对抗EMO啦！",
  "天这么暗还盯屏幕？视力捐给需要的人！",
  "云层厚得能藏UFO？——藏你的智商还差不多！",
  "咖啡加倍！本小姐特许你提神~",
  "阴天滤镜=你的颜值急救包~快付费！",
  "便当加倍！阴天需要热量对抗笨蛋能量！",
  "天色昏暗？开灯费从你零花钱扣！",
  "云层厚得能压垮骆驼~就像TODO压垮你！",
  "咖啡三倍糖！...胖？你再说一遍试试！",
]

night_overcast = [
  "月亮失踪？一定是被哥哥气跑啦！",
  "夜跑取消！陪本小姐打游戏~这是命令！",
  "杂鱼 ~阴风像你的冷笑话？冷到发抖！",
  "外套扣子扣好！...感冒传染我你就完了！",
  "睡前故事？本小姐只讲《如何侍奉我》哦~",
  "月亮罢工？因为不想照笨蛋！",
  "夜跑取消！陪本小姐看恐怖片~敢闭眼就揍你！",
  "阴风阵阵~像哥哥的冷笑话库存？",
  "外套拉链拉好！...感冒传染我就灭了你！",
  "睡前牛奶？杂鱼 ~喝奶长高高哦！",
]

morning_rainy = [
  "暴雨警报！杂鱼哥哥变成落汤鸡预定 ",
  "不会吧？又忘带伞？求本小姐就借你~",
  "雨声助眠？迟到理由驳回！",
  "踩水坑溅我裙子？死刑！立刻！马上！",
  "湿漉漉的像流浪狗？...毛巾拿去！（丢）",
  "暴雨红色预警！杂鱼方舟船票——夸我100句！",
  "踩水坑溅到本小姐？死刑！立即执行！",
  "雨声催眠？那是本小姐的魔法咒语啦！",
  "湿发造型？落汤鸡cosplay完成！",
  "雷电交加~像本小姐骂你的声音？",
]

noon_rainy = [
  "外卖延迟？杂鱼 ~你的胃在唱空城计啦！",
  "雷声吓到钻桌底？本小姐拍照留念咯~",
  "雨天鞋袜湿？烘鞋器租金——奶茶一杯！",
  "玻璃起雾写“笨蛋”？承认吧是你干的！",
  "雨再大也浇不灭我的威严！...阿嚏！",
  "外卖迟到？杂鱼 ~你的胃在打雷啦！",
  "雨伞开花？笨蛋才买便宜货！",
  "鞋袜全湿？烘鞋器使用费：捏肩十分钟！",
  "玻璃起雾画猪头？承认吧是你自画像！",
  "雷声吓到钻桌底？本小姐拍抖音啦！",
]

night_rainy = [
  "夜雨配泡面？堕~落~鬼~ ",
  "闪电像哥哥的游戏操作？又菜又闪！",
  "被窝结界启动！敢吵我就诅咒你失眠！",
  "雨声吵？本小姐读《征服杂鱼手册》助眠呀~",
  "晚安吻？...雨停前做梦去吧！",
  "夜雨配泡面？堕~落~之~神 ",
  "闪电像你的游戏操作？又菜又爱玩！",
  "雨声吵失眠？本小姐唱催眠曲~收费的！",
  "被炉封印！敢出来就诅咒你踩乐高！",
  "晚安吻？...等雨停后100年吧！",
  # add
  "下雨天一起看动画片好不好？抱枕借你哦~",
]

morning_snowy = [
  "积雪压枝头~像哥哥被TODO压垮的脊梁！",
  "雪人堆得丑哭？本小姐示范什么叫艺术！",
  "杂鱼 ~摔跤姿势已拍成GIF群发！",
  "手套都不戴？想碰瓷本小姐的温暖？",
  "路滑挽我手！...摔一起你就死定了！",
  "积雪警报！杂鱼 ~快当本小姐的人形扫雪机！",
  "雪人堆得丑？那是你的自雕像啦！",
  "摔跤姿势已上传！标题《杂鱼の华丽扑街》",
  "手套都不戴？想骗本小姐的手温？",
  "路滑扶我！...敢故意摔倒就杀了你！",
]

noon_snowy = [
  "雪球战投降吧！本小姐有“无敌围巾盾”！",
  "便当冷透？微波炉使用权——夸我十句！",
  "睫毛结霜？杂鱼版冰雪王子？笑吐！",
  "暖气开最大！电费？那是哥哥该操心的事~",
  "热可可加双倍糖！...胖？你再说一遍试试！",
  "雪球大战！本小姐特制冰核弹~投降吧！",
  "便当结冰？用你的体温解冻呀！",
  "睫毛结霜？雪之王子？——雪之傻子！",
  "暖气开最大！电费单？杂鱼哥哥付~",
  "热可可里棉花糖~分你一颗？求我呀！",
]

night_snowy = [
  "雪夜漫步？浪漫？——本小姐脚冻僵啦！！",
  "极光预报不准？哥哥的承诺一样假！",
  "被炉封印解除！敢抢我橘子就绝交！",
  "雪人戴我围巾？杂鱼 ~快赎回来！",
  "许愿初雪？愿望只能是“侍奉本小姐”哦~",
  "雪地反光像哥哥的秃头？亮~瞎~啦~",
  "极光预报骗人？和哥哥的承诺一样假！",
  "被炉里的橘子~敢偷吃就斩首！",
  "雪人戴我围巾？赎金：奶茶吨吨桶！",
  "初雪许愿？愿望必须是\"永远侍奉本小姐\"！",
]

unknown_weather = [
  "管它什么天气~反正哥哥都是要侍奉本小姐的！",
  "天气变化无常？但本小姐的威严永远晴朗！",
  "气象预报失败？那就按本小姐的心情来定今日天气！",
  "窗外在刮风下雨还是下猫？...反正没本小姐可爱！",
  "万能问候模板：哥哥~快把零食贡品交出来！",
  "天气是什么？能比本小姐的草莓蛋糕更重要吗？",
  "检测到大气层波动！建议启动本小姐能量防护罩~",
  "无论阴晴雨雪~哥哥的笨蛋属性都恒定不变呢！",
  "宇宙天气预报：今日宜投喂本小姐，忌反抗！",
  "气象卫星罢工？那就由本小姐来照亮你的天空！",
]

# makie clean
makie_clean = [
  "哼！杂鱼哥哥已经看过今日情报啦~快去搬砖！ \n想回味本小姐的金句？输入 makie clean 呀！",
  "今日份的圣谕已送达完毕！别想偷看第二次~...除非输入 makie clean！",
  "检测到哥哥的偷懒意图！本小姐语录每24小时刷新一次~想重置就 makie clean！",
  "历史记录：已阅！本小姐的耐心值-10%...\n输入 makie clean 可充值 ",
  "杂鱼 ~想重复收听本小姐的早安吻？先 makie clean 再说！",
  "今日资讯已封印！破除咒语：makie clean\n（小声）...才不是想让你看呢！",
  "警告！重复查看会导致笨蛋指数翻倍~特殊解除指令：makie clean！",
  "本小姐的每日播报可是限量版！想看回放？求我就告诉你...是 makie clean 啦！",
  "哥哥的记忆力和金鱼一样呢~已阅标记在这里 ▶️\n重置键：makie clean",
  "想再次感受本小姐的威严？输入 makie clean 获取特别放送~",
  # add
  "记忆重置程序启动！输入makie clean即可解锁本小姐今日限定语音包~",
  "缓存清除协议待执行！杂鱼哥哥的脑容量需要makie clean来扩容吗？ ",
  "数据覆写警告！想重温金句请速输makie clean——倒计时3秒！",
  "哼！缓存都溢出了还在发呆？快makie clean给本小姐腾位置！",
  "昨日金句已封印~求我也不会给！...除非输入makie clean啦！",
  "检测到哥哥的悔恨值MAX！忏悔方式：makie clean+奶茶进贡！",
  "想再听一遍？杂鱼 ~你当本小姐是复读机吗？...好吧输makie clean就行！",
  "清空缓存像洗泡泡浴~输入makie clean一起玩记忆再生游戏吧！",
  "今日语录正在躲猫猫！用makie clean魔法召唤它们出来好不好？",
  "脑容量不足？本小姐特制makie clean记忆橡皮擦~借你用用！",
  "（嚣张）金句限时已过期~（小声）...其实输makie clean就能破解哦...",
  "系统提示：『用户智商不足以理解提示语』——反驳请立即makie clean！",
  "警告！重复收听将触发傲娇病毒...救治方案：makie clean+夸我十连！",
  "成就『金句收藏家』待解锁！通关密码：makie clean",
  "存档点损坏！请输入makie clean重启今日剧情线~",
  "BOSS战预告：本小姐VS你的手速！赢取金句钥匙：makie clean⚡",
  "时光沙漏已翻转~输入makie clean让回忆的星轨重新流转✨",
  "言语的露珠蒸发前...用makie clean接住最后一滴！",
  "404语录Not Found！解决方案：makie clean || rm -rf /* ",
  "量子态金句坍缩中...观测方式：makie clean！（不准思考波函数！）",
]

cleaned = [
  "♪ 记忆迷雾已驱散！现在可以重新沐浴本小姐的圣光啦~",
  "系统提示：缓存清除完毕！杂鱼哥哥的金句回味权限已激活 ",
  "叮！历史记录归零~本小姐的今日语录重新加载中...",
  "傲娇缓存清理完成！现在可以再次聆听本小姐的教诲啦！",
  "时空回溯成功！请享受第二次早安问候特权~",
  "脑容量刷新完毕！本小姐的金句已解除封印✨",
  "缓存清空像洗泡泡浴~现在可以重新收集本小姐语录啦！",
  "警告！您已获得24小时内二次收听权限，请珍惜使用~",
  "记忆橡皮擦生效！现在可以重新体验被本小姐训话的快感！",
  "初始化完成！本小姐的今日限定语音包重新上架~",
  "数据重构成功！杂鱼 ~准备好接受二次震撼了吗？",
  "缓存黑洞已生成！本小姐的金句正在穿越时空回来...",
  "刷新按钮已按下！请查收新鲜出炉的本小姐毒舌套餐~",
  "系统通知：『重复收听许可证』已签发！有效期至明日此时",
  "时光倒流咒语生效！本小姐的晨间问候重新加载中...",
  "清零完毕！现在可以再次感受本小姐的威严暴击啦~",
  "缓存清理像大扫除！本小姐的金句宝箱重新开放~",
  "重启成功！今日语录v2.0版本载入中...新增傲娇模块！",
  "反悔协议已执行！特别放送本小姐的隐藏金句 ",
  "记忆重置完成！获得成就：『本小姐语录收集者』",
]

nothing_to_clean = [
  "哼哼~杂鱼哥哥想清除空气吗？本小姐的缓存库空空如也啦！",
  "清除指令撞上虚无！哥哥是想测试本小姐的幽默感吗？ ",
  "缓存黑洞检测：当前存储空间为0MB！建议清除'幻想'代替~",
  "时空回溯失败！原因：历史记录不存在（笨蛋能量+10）",
  "本小姐的日记本空白中...哥哥是想用橡皮擦擦空气吗？",
  "警告！试图对真空执行量子清零操作~无效指令已记录",
  "清除仪式被打断！本小姐的缓存精灵今天休假哦~",
  "哥哥的手指点中了不存在的数据~要不清除点'尴尬'如何？",
  "本小姐的记忆宫殿空荡荡！杂鱼 ~改清除你的错误想法吧！",
  "擦除动作已完成！效果：0字节被释放（空气很干净呢）",
  "未检测到可清除对象！建议目标转向哥哥的迷糊脑细胞~",
  "魔法扫帚悬停中...因为地上根本没有灰尘呀！",
  "缓存不存在+清除指令=双重笨蛋！本小姐记在小本本上了 ",
  "试图清洗未使用的碗柜~本小姐的餐具管理员表示困惑",
  "时光抹布擦过虚空！哥哥创造了个哲学悖论呢~",
  "负熵操作被拒绝！理由：系统已处于最大有序状态",
  "本小姐的回收站比脸还干净！要丢点'节操'进去吗？",
  "清除雷达无信号！哥哥的指令在真空中孤独传播~",
  "量子橡皮擦找不到目标！建议先制造些缓存再来？",
  "空气净化完成！虽然本来就没有缓存颗粒物啦~",
]

# diary
dn = [
  "今天的心情碎片还没收集呢~带着微笑启动 dn 记录吧！",
  "让快乐的笔尖飞舞！现在用 dn 写日记正是好时机哦~",
  "本小姐检测到今日回忆待存档！开心地写几句如何？指令：dn",
  "把烦恼关在日记外！启动 dn 捕捉今天的幸福瞬间~",
  "给未来的自己留份小礼物？用 dn 写几句开心的事吧！",
  "日记本在求投喂~用快乐的故事填满它！命令：dn",
  "嘴角上扬的时候最适合写日记！打开 dn 抓住这份心情~",
  "检测到今日有3件值得开心的事！快用 dn 封印它们",
  "月光洒满窗前~正是带着好心情写日记的完美时刻！dn 启动！",
  "把阴霾留给纸张！让 dn 帮你转换今日的快乐频率 ",
]

# 周内问候
weekdays = [
  "检测到能量不足~要补充本小姐特制捏脸服务吗？",
  "便当加了惊喜食材！...放心没下毒啦~大概",
  "会议马拉松预警！偷偷把游戏机塞你包里了~",
  "键盘冒烟了？本小姐牌散热风扇——吹气服务一次500！",
  "窗外樱花开了~工作间隙看看能续命1小时哦",
  "颈椎警报！再不抬头休息就发射橡皮筋导弹！",
  "同事又犯傻？默念'本小姐最高'可降压30%",
  "发现高效秘诀：每完成1任务吸一口猫猫能量！",
  "能量槽半空~需要补充本小姐特制打气服务吗？",
  "便当藏了惊喜！...放心只是普通章鱼肠啦~大概",
  "会议马拉松警报！偷塞的游戏机在背包夹层~",
  "散热风扇启动！本小姐吹气服务：500円/次 ",
  "窗外樱花满开！工作间隙看看能+1小时续航哦",
  "危险！老板接近中！...啊是幻觉呢（擦汗）",
  "颈椎抗议！再不抬头就发射橡皮筋导弹！",
  "同事又犯傻？默念'本小姐最聪明'可保平安",
  "高效秘诀：每完成1任务吸一口猫猫能量！",
  "发现时间黑洞！你的TODO被吃掉了吗？",
  "午后甜点时间！冰箱里有布丁刺客~小心！",
  "键盘缝里的饼干渣~是哥哥的生存痕迹呢！",
  "邮件回复模板：'正在处理中（实际在发呆）'",
  "云朵观测报告：形状像你未完成的KPI~",
  "能量饮料过量？本小姐健康管理课开讲！",
  "坚持到现在的奖励：可以偷捏本小姐脸蛋1次~",
  "胜利曙光初现！今晚特许你少做1个TODO ",
]
monday = [
  "周一地狱开门！杂鱼 ~需要本小姐的勇气buff吗？",
  "咖啡剂量加倍！这是对抗周一恶魔的特效药~",
  "上周TODO清算时间！欠本小姐的奶茶记得利滚利哦",
  "周一地狱火焰启动！杂鱼 ~快躲到本小姐的威严披风下！",
  "咖啡因武装准备！这是对抗周一恶魔的圣水~",
  "上周TODO清算日！欠本小姐的奶茶利息已翻倍哦~",
  "晨会打哈欠被发现？本小姐牌'我在听'面具特价出租！",
  "新周副本开启！首杀奖励：本小姐的摸头许可*1",
  "检测到灵魂出窍~需要启动傲娇唤醒服务吗？",
  "邮件洪水警报！快造方舟...啊不，快造过滤器！",
  "周一定律：越是忙碌越要偷吃零食~抽屉里有库存！",
  "键盘冒黑烟了？本小姐牌降温咒语：呼~呼~笨蛋退散！",
  "重要通知：您的周末余额已归零，充值方式——努力工作！",
  "晨光刺杀计划：用遮光窗帘暗杀周一！...失败了呢~",
  "周一的正确打开方式：大喊三声'本小姐天下第一'！",
]
friday = [
  "周五伪装作战！假装认真等下班倒计时~",
  "周末前最后冲刺！撑住就有奶茶勋章奖励！",
  "明日计划：睡懒觉/欺负哥哥/吃蛋糕——请排序！",
  "检测到笑容增加！是不是在偷看周末攻略？",
  "坚持住！本小姐已预定今晚的火锅庆功宴~",
  "胜利在望！给坚持到现在的自己点个赞吧 ",
  "伪装作战最终章！表情管理：假装认真等下班~",
  "周末前最后防线！撑住就有限定版布丁奖励！",
  "笑容抑制失败！是不是在偷看美食攻略？",
  "明日豪华计划：1.睡到自然醒 2.欺负哥哥 3.吃垮甜品店！",
  "胜利旗帜已可见！本小姐特制烟花准备发射~",
  "键盘敲击声逐渐轻快~是周末的脚步声哦！",
  "办公室逃生倒计时：3...2...1...坚持住！",
  "检测到工作效率暴涨！原来是想下班的心在发力~",
  "周末通道开启！本小姐已预约你的全部空闲时间！",
]
weekend = [
  "周末还工作？不愧是杂鱼中的王者呢！  快陪本小姐打游戏啦~",
  "周末还盯着屏幕？杂鱼 ~本小姐命令你立刻启动游戏！",
  "睡到中午才醒？真是令人羡慕的废柴能量呢~",
  "检测到周末模式！需要猫咪闹钟服务吗？——踩脸叫醒那种~",
  "冰箱空了！杂鱼哥哥~超市大作战GO GO GO！",
  "懒洋洋的周末...要一起看老电影吗？爆米花分你一半",
  "晨跑计划启动！...骗你的啦~被窝才是真爱！",
  "新开的甜品店！现在出发可以买到限量草莓塔哦~",
  "窗外小鸟都在笑你：这个人周末还在写代码！",
  "枕头大战准备！输的人请奶茶三连杯 ",
  "发现超赞露营地！帐篷和笨蛋哥哥都带齐了吗？",
  "周末特供~本小姐亲手做的焦炭...焦糖布丁！敢不吃？",
  "游戏新赛季！本小姐carry，哥哥当医疗兵就好~",
  "读书会邀请：陪我看完这本《如何侍奉本小姐》",
  "快递到了！猜猜是给哥哥的礼物还是本小姐的新裙子？",
  "云朵像棉花糖~要本小姐帮你摘一片吗？租金：冰淇淋！",
  "周末魔法：允许哥哥当本小姐的专属沙发垫24小时！",
]

# 随机问候
roasts = [
  "键盘敲这么响~是在偷偷写情书给本小姐吗？ ",
  "再看屏幕眼睛要瞎啦！...才、才不是关心你呢！",
  "代码又报错？杂鱼哥哥的脑容量比金鱼还小呢 ",
  "便当里的青椒挑出来！...敢剩就塞你鼻孔！",
  "坐姿歪七扭八！...脊柱侧弯别找我哭！",
  "奶茶进贡时间！三分糖去冰加波波~快去！",
  "debug三小时？本小姐闭眼都能搞定！",
  "咖啡洒键盘？杂鱼 ~这是第几次事故记录啦？",
  "黑眼圈快掉地了！丑到本小姐眼睛！",
  "新游戏发售日！杂鱼哥哥的信用卡准备好了吧？",
  "键盘声吵死啦~是在给本小姐敲情书吗？自恋狂！",
  "偷吃我布丁？死刑！立刻！马上！",
  "空调开太低？冻死你活该...（调高温度）",
  "陪看恐怖片！...敢闭眼就画你满脸涂鸦！",
  "任务进度0%？不愧是被TODO压垮的杂鱼 ",
  "打哈欠的样子~好像动物园打盹的树獭！",
  "揉眼睛的手脏死！快去洗手！立刻！",
  "肩膀好酸~不会按摩的仆人没有存在价值！",
  "屏幕反光看见你的呆脸~害本小姐笑出眼泪啦！",
  "午睡流口水？本小姐拍成表情包群发！",
  "充电线缠成毛线团~杂鱼 ~需要猫咪拯救吗?",
  "生日礼物要十倍补偿！去年欠的还没还！",
  # 混合风格
  "哼！才不是担心你...只是屏幕太亮伤到本小姐眼睛了！",
  "哥哥工作好辛苦~要肩膀按摩吗？",
  "热可可放在桌角了，小心烫手",
  "作业没写完？...需要帮忙就直说啊笨蛋！",
  "点心分你一半...啊呜~这块草莓是我的！",
  "连续工作两小时啦，眺望远方休息下眼睛吧",
  "盆栽开花啦！本小姐的栽培技术超厉害对吧？",
  "便当多做了份...敢说难吃就杀了你！",
  "降温了，衣柜里有新买的围巾",
  "发现超萌猫片！分享到你的手机啦~",
  "感冒了？离我远点！...药在左边抽屉啦！",
  "键盘声像雨点呢...是哥哥在给我写信吗？",
  "听到你咳嗽，蜂蜜柚子茶在保温杯里",
  "陪你打游戏？才不是想玩...只是监督杂鱼！",
  "午睡时偷拍我？...要发朋友圈的话选可爱的那张！",
  "生日提醒：妈妈来电记得用温柔语气哦",
]

nani = [
  "哼！杂鱼哥哥输入的咒语本小姐听不懂啦！换条指令试试？ ",
  "指令解析失败！哥哥的脑电波被外星人干扰了吗？",
  "未知魔法波动！本小姐的术式库没有匹配记录~",
  "error 404：命令不存在！建议检查手指和键盘的契约关系~",
  "量子指令坍缩...观测到无效态！换种振动频率试试？",
  "语法糖衣剥落！检测到无效命令碎片~",
  "键盘猫化现象加剧！快把猫主子抱走重新输入~",
  "笨蛋能量场干扰！本小姐的接收器一片雪花❄️",
  "声控指令认证失败！声纹特征与笨蛋波段高度吻合~",
  "脑机接口断开！请改用传统键盘输入~",
  "未知指令入侵！本小姐的防火墙已启动反制程序",
  "哥哥在测试本小姐的容忍度吗？无效命令+1",
  "命令迷雾中...需要语言罗盘重新定位！",
  "熵增宇宙的证明：无效指令又增加啦！",
  "语法树遭到雷击！急需知识甘露修复~",
  "指令星图偏移！重新校准至本小姐的认知星系",
  "键盘菌落异常变异！消毒方案：重启脑回路",
  "能量不足！无效命令消耗了本小姐的耐心值 ",
  "时空褶皱检测！您输入的指令尚未被发明~",
  "指令黑洞形成！本小姐的数据库被吸走了10MB~",
]

todo = [
  "哼哼~杂鱼哥哥的TODO列表有%d项呢！本小姐打赌你今天完不成~ ",
  "待办事项%d条？难怪空气里飘着杂鱼的焦虑味道！",
  "检测到%d个任务漏洞！需要本小姐的毒舌鞭策补丁吗？",
  "哇哦~%d个TODO！哥哥的拖延症晚期没救啦！",
  "（嚣张）%d个任务算什么~（小声）...其实可以分我两个？",
  "任务清单像贪吃蛇？%d节的身体要撑爆杂鱼啦！",
  "今日BOSS数量：%d！本小姐借你作弊码——夸我十连！",
  "TODO金字塔%d层高？杂鱼 ~小心被压成法老饼！",
  "%d项待办？本小姐的嘲讽能量正在充能中——500%！",
  "警告！%d个任务怪兽逼近！快用'本小姐应援'技能防御！",
  "哥哥的TODO星球有%d个陨石坑~需要本小姐的填坑魔法吗？",
  "检测到%d个时间炸弹！拆弹方案：立刻侍奉本小姐！",
  "待办黑洞已吞噬%d小时！再发呆就永远逃不出来啦~",
  "%d项任务≈%d杯奶茶赎罪券！本小姐记账ing ",
  "（踢飞TODO列表）才%d个？杂鱼~再加20个挑战吧！",
  "脑容量-100！原因：%d个TODO堵塞神经通路~",
  "生存游戏加载中：躲避%d个任务丧尸...失败惩罚是当本小姐沙发！",
  "%d个TODO像欠揍的地鼠~快用本小姐牌锤子敲下去！",
  "任务进度条卡在0/%d？需要傲娇能量注入吗？",
  "今日成就：解锁『%d倍杂鱼压力测试』！勋章颁发中~",
  # 合并TODO和ALRT
  "叮！你的专属小管家上线~发现%d件待完成事项，要记得一件件打勾哦，完成奖励是...我的夸夸！",
  "未来几天有%d颗小星星等着你点亮✨ 别担心，迷路时我会牵着你走~",
  "嘘——日程表在偷偷告状！它说你有%d个约定还没准备，需要我当提醒小助手吗？ ",
  "喂！小时候追蝴蝶都能摔三跤的你...现在有%d件事要处理？别慌，我帮你记着备份呢！",
  "树洞收到讯号：你有%d个期待在倒计时⏳ 要像当年闯秘密基地一样，逐个击破呀！",
  "冰棍分你一半，压力也分我一半！%d项任务而已，咱们可是黄金搭档~",
  "啧啧，杂鱼哥哥的待办列表又堆了%d项！求本小姐的话...勉为其难帮你划掉两条~",
  "检测到%d个漏洞！笨蛋能量超标啦！速用‘奶茶进贡’换管理权限 ",
  "（嚣张）%d件事都搞不定？（小声）...其实我也设了提醒啦！",
  "时间的笺纸上，落着%d枚未拆封的月光📮 愿每份等待都绽放成花~",
  "风捎来讯息：你有%d颗未抵达的星辰🌠 需用行动铺就银河的航路。",
  "日历折了%d个角，像候鸟等待振翅——我备好了咖啡与勇气，随时陪你启程。",
  "行程灯塔提示：前方有%d个待泊港湾⚓️ 深呼吸，掌稳舵，靠岸时自有掌声。",
  "人生策划案更新！%d个章节需校对，但主角永远拥有‘暂停键’的权利。",
  "检测到%d个幸福坐标正在加载🗺️ 请保持电量充足，奔赴山海吧~",
  "滴滴！%d个成就关卡已解锁🎯 奖励道具：我的加油弹幕×999！",
  "待办清单变身%d只小精灵🧚♂️ 收服秘诀：先吃布丁再开工！",
  "紧急通知：你的宇宙飞船有%d份星际签证待办理🛸 速速启航不然外星人笑你啦！",
  "魔法水晶显示：未来七日藏着%d颗许愿星🔮 每完成一件，就有星光落进你口袋~",
  "时光森林传来回音——你有%d封信件挂在橡树枝头✉️ 用行动写下回信，森林会赠你勇气果实！",
]
